version: '3.8'

services:
  react-app:
    build: .
    container_name: mmhs_react
    restart: always
    ports:
      - "${PORT:-2087}:${PORT:-2087}"
    env_file:
      - .env
    volumes:
      - .:/app
    command: yarn dev --host --port 2087