version: '3.8'

services:
  react-app:
    build: .
    container_name: mmhs_react
    restart: always
    ports:
      - "2087:2087"
    volumes:
      - .:/app
    command: yarn dev --host --port 2087